name: dividas
description: "trackear as dividas do fdp"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  line_icons: ^2.0.3

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/icone.png"

flutter:
  uses-material-design: true
