// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyL1crqeKAtjchuCrUcBtcMD81E9CyiTY',
    appId: '1:258386124698:android:825d3344d92b82fbb3e423',
    messagingSenderId: '258386124698',
    projectId: 'dividasapp-43559',
    storageBucket: 'dividasapp-43559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAia4D7_bOcHCPJfC2jra73FD5ybXW33Ks',
    appId: '1:258386124698:ios:d7018081a648311ab3e423',
    messagingSenderId: '258386124698',
    projectId: 'dividasapp-43559',
    storageBucket: 'dividasapp-43559.firebasestorage.app',
    iosBundleId: 'com.example.dividas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBArYSZLUb7FLXfQiAPknizMdfgdq9Dpg',
    appId: '1:258386124698:web:6cdaab8d6ed31e06b3e423',
    messagingSenderId: '258386124698',
    projectId: 'dividasapp-43559',
    authDomain: 'dividasapp-43559.firebaseapp.com',
    storageBucket: 'dividasapp-43559.firebasestorage.app',
  );
}
